<Project Sdk="Microsoft.NET.Sdk.Web">
    
    <ItemGroup>
      <Content Include="..\..\.dockerignore">
        <Link>.dockerignore</Link>
      </Content>
      <Content Update="Pages\Challenges\_SampleOutput.cshtml">
        <DependentUpon>_ChallengeRows.cshtml</DependentUpon>
      </Content>
    </ItemGroup>
    
    <ItemGroup>
      <ProjectReference Include="..\SqlServerChallenges.Core\SqlServerChallenges.Core.csproj" />
    </ItemGroup>
    
    <ItemGroup>
      <AdditionalFiles Include="Pages\Challenges\_ChallengeRows.cshtml" />
    </ItemGroup>

</Project>
